version: 0.0
os: linux
files:
  - source: test.txt
    destination: /home/ubuntu/test_codedeploy/test.txt
  - source: Har_Website.py
    destination: /home/ubuntu/test_codedeploy/Har_Website.py
  - source: Scrapy_Har/Scrapy_Har/spiders/Har_Test_AWS.py
    destination: /home/ubuntu/test_scrapy/test_spider/test_spider/spiders
