version: 0.2

phases:
  install:
    runtime-versions:
      python : 3.7
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - buildspec.yml
    - appspec.yml
    - test.txt
    - Har_Website.py
    - Scrapy_Har/Scrapy_Har/spiders/Har_Test_AWS.py
cache:
  paths:
    - '/home/ubuntu/test_codedeploy/test.txt'
    - '/home/ubuntu/test_codedeploy/Har_Website.py'
    - '/home/ubuntu/test_scrapy/test_spider/test_spider/spiders/Har_Test_AWS.py'
 

